# Generated by Django 5.1.1 on 2024-09-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('event_type', models.CharField(max_length=255)),
                ('custom_event', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
