# Generated by Django 5.1.1 on 2024-09-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
